In [1]:
import numpy as np

In [2]:
inp = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
out = np.array([0, 0, 0, 1])

In [3]:
inp, out

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 0, 0, 1]))

In [4]:
threshold_and = 1.5

In [5]:
AND_Gate = np.array(list(map(lambda x: 1 if np.sum(x) > threshold_and else 0, inp)))
AND_Gate

array([0, 0, 0, 1])

In [6]:
np.allclose(out, AND_Gate)

True

In [7]:
inp = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
out = np.array([0, 1, 1, 1])

In [8]:
inp, out

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 1, 1]))

In [9]:
threshold_or = 0.5

In [10]:
OR_Gate = np.array(list(map(lambda x: 1 if np.sum(x) > 0.5 else 0, inp)))
OR_Gate

array([0, 1, 1, 1])

In [11]:
np.allclose(out, OR_Gate)

True