In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1-x)

In [4]:
inp_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
out_data = np.array([[0], [1], [1], [0]])

In [5]:
inp_data, out_data

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0],
        [1],
        [1],
        [0]]))

In [6]:
inp_neurons = 2
hid_neurons = 4
out_neurons = 1

In [7]:
weights_input_hidden = 2 * np.random.random((inp_neurons, hid_neurons))-1
weights_hidden_output = 2 * np.random.random((hid_neurons, out_neurons))-1

In [8]:
weights_input_hidden

array([[ 0.45109075, -0.66063534,  0.2409503 ,  0.55924662],
       [ 0.70868826, -0.02846852, -0.39078254,  0.47932506]])

In [9]:
weights_hidden_output

array([[-0.63405834],
       [ 0.75038695],
       [-0.21215994],
       [-0.79331647]])

In [10]:
epochs = 10000
lr = 0.5

In [11]:
for i in range(epochs):
    ## Feed Forward
    hidden_layer_output = sigmoid(np.dot(inp_data, weights_input_hidden))
    output_layer_output = sigmoid(np.dot(hidden_layer_output, weights_hidden_output))

    ## Calculate Error of Output Layer
    output_error = out_data - output_layer_output

    ## Back-Propogation
    delta_output_layer_output = output_error * sigmoid_derivative(output_layer_output)
    new_output_layer_weights = lr * np.dot(hidden_layer_output.T, delta_output_layer_output)

    ## Calculate Error of Hidden Layer
    hidden_error = np.dot(delta_output_layer_output, weights_hidden_output.T)

    ## Back-Propogation
    delta_hidden_layer_output = hidden_error * sigmoid_derivative(hidden_layer_output)
    new_hidden_layer_weights = lr * np.dot(inp_data.T, delta_hidden_layer_output)

    ## Updating Weights 
    weights_input_hidden += new_hidden_layer_weights
    weights_hidden_output += new_output_layer_weights

In [12]:
hidden_layer_output = sigmoid(np.dot(inp_data, weights_input_hidden))
output_layer_output = sigmoid(np.dot(hidden_layer_output, weights_hidden_output))

In [13]:
np.round(output_layer_output)

array([[0.],
       [1.],
       [1.],
       [0.]])

In [14]:
output_layer_output

array([[0.03914592],
       [0.96588608],
       [0.96734693],
       [0.02582113]])

In [15]:
weights_input_hidden

array([[-2.74275439, -7.35044177,  2.44700921, -5.08395137],
       [ 5.37370078,  3.73631683, -4.74476894, -5.0258967 ]])

In [16]:
weights_hidden_output

array([[ -4.51665767],
       [  8.08388116],
       [  4.06706545],
       [-14.03534174]])